@api = http://localhost:8080/api/Users

GET {{api}}

###

POST {{api}}
Content-Type: application/json

{
    "userId": "70fb7a17-16a4-4e0d-be40-dbbd16ea159d",
    "userName": "Sigma",
    "password": "U2FsdGVkX19Vo1g5EFxWaNkFeBUB6pnnZPb29kG5dj0=",
    "userMail": "test@gmail.com",
    "phoneNumber": "4181121125"
}

###

POST {{api}}
Content-Type: application/json

{
    "userId": "70fb7a17-16a4-4e0d-be40-dbbd16ea159e",
    "userName": "Sigma2",
    "password": "U2FsdGVkX19Vo1g5EFxWaNkFeBUB6pnnZPb29kG5dj0=",
    "userMail": "test2@gmail.com",
    "phoneNumber": "4181121125"
}

###

DELETE {{api}}/70fb7a17-16a4-4e0d-be40-dbbd16ea159e


###

PUT {{api}}/70fb7a17-16a4-4e0d-be40-dbbd16ea159d
Content-Type: application/json

{
    "userId": "70fb7a17-16a4-4e0d-be40-dbbd16ea159d",
    "userName": "Sigma",
    "password": "U2FsdGVkX19Vo1g5EFxWaNkFeBUB6pnnZPb29kG5dj0=",
    "userMail": "test@gmail.com",
    "phoneNumber": "4181121125"
}